@extends('layouts.app')

@section('content')
<div data-report-page class="space-y-6">
    <section class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-sm font-medium text-brand-600">Analisis lokal</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Laporan Keuangan</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Semua kalkulasi dilakukan di perangkatmu.</p></div><button data-report-export disabled class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50">↓ Export CSV</button></section>
    <section class="grid grid-cols-1 gap-3 rounded-2xl border border-gray-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-5 dark:border-gray-800 dark:bg-white/[0.03]"><input data-report-from type="text" readonly aria-label="Tanggal mulai" class="h-11 cursor-pointer rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><input data-report-to type="text" readonly aria-label="Tanggal akhir" class="h-11 cursor-pointer rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><select data-report-type class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"><option value="">Semua tipe</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option><option value="transfer">Transfer</option><option value="adjustment">Adjustment</option></select><select data-report-account class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"><option value="">Semua akun</option></select><select data-report-category class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"><option value="">Semua kategori</option></select></section>
    <p data-report-error class="hidden rounded-xl bg-error-50 px-4 py-3 text-sm text-error-700"></p>
    <section class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Pemasukan</p><p data-report-income class="mt-2 text-xl font-bold text-success-600">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Pengeluaran</p><p data-report-expense class="mt-2 text-xl font-bold text-error-600">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Cashflow bersih</p><p data-report-net class="mt-2 text-xl font-bold text-gray-900 dark:text-white">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Jumlah transaksi</p><p data-report-count class="mt-2 text-xl font-bold text-gray-900 dark:text-white">0</p></article></section>
    <section class="grid grid-cols-1 gap-6 xl:grid-cols-3"><article class="overflow-hidden rounded-2xl border border-gray-200 bg-white xl:col-span-2 dark:border-gray-800 dark:bg-white/[0.03]"><header class="border-b border-gray-100 px-5 py-4 dark:border-gray-800"><h3 class="font-semibold text-gray-900 dark:text-white">Rincian transaksi</h3></header><div class="overflow-x-auto"><table class="w-full"><thead><tr class="bg-gray-50 text-left text-xs font-medium uppercase text-gray-500 dark:bg-white/[0.03]"><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Transaksi</th><th class="px-5 py-3">Akun</th><th class="px-5 py-3 text-right">Nominal</th></tr></thead><tbody data-report-rows></tbody></table></div></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-900 dark:text-white">Pengeluaran per kategori</h3><p class="mb-6 mt-1 text-sm text-gray-500">Berdasarkan filter aktif.</p><div data-report-categories class="space-y-5"></div></article></section>
</div>
<div data-report-toast class="app-toast hidden"></div>
@endsection
