@extends('layouts.app')

@section('content')
<div data-diagnostics-page class="space-y-6">
    <section class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-sm font-medium text-brand-600">Quality assurance lokal</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">PWA Diagnostic</h2><p class="mt-1 max-w-2xl text-sm text-gray-500">Periksa kesiapan teknis otomatis, lalu selesaikan skenario offline secara manual.</p></div><div class="flex gap-2"><button data-export-diagnostic disabled class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium disabled:opacity-40 dark:border-gray-700">Export hasil</button><button data-run-diagnostics class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Jalankan diagnostic</button></div></section>
    <section class="grid gap-6 xl:grid-cols-2"><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] sm:p-6"><div class="flex items-center justify-between gap-3"><div><h3 class="font-semibold text-gray-900 dark:text-white">Pemeriksaan otomatis</h3><p data-diagnostic-summary class="mt-1 text-sm text-gray-500">Belum dijalankan</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10">⌁</span></div><div data-diagnostic-results class="mt-4"><p class="py-10 text-center text-sm text-gray-500">Tekan Jalankan diagnostic untuk memulai.</p></div></article>
        <article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] sm:p-6"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-gray-900 dark:text-white">Acceptance manual</h3><p class="mt-1 text-sm text-gray-500">Centang hanya setelah skenario benar-benar berhasil.</p></div><span data-manual-progress class="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">0/0 selesai</span></div><div data-acceptance-list class="mt-5 grid gap-2"></div><label class="mt-4 block text-sm font-medium text-gray-700 dark:text-gray-300">Catatan perangkat dan kendala<textarea data-acceptance-notes rows="4" class="mt-1.5 w-full rounded-lg border border-gray-300 bg-transparent p-3 text-sm outline-none focus:border-brand-500 dark:border-gray-700" placeholder="Contoh: Firefox 153, macOS, restore berhasil…"></textarea></label><button data-save-acceptance class="mt-4 w-full rounded-lg bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-gray-900">Simpan checklist</button></article></section>
    <section class="rounded-2xl border border-warning-200 bg-warning-50 p-5 text-sm text-warning-800 dark:border-warning-800 dark:bg-warning-500/10 dark:text-warning-300"><b>Catatan:</b> diagnostic otomatis tidak dapat mematikan server, jaringan, atau browser. Skenario tersebut wajib diuji manual dan dicentang setelah berhasil.</section>
    <div data-diagnostics-toast class="app-toast hidden"></div>
</div>
@endsection
