import { ACCEPTANCE_ITEMS, runDiagnostics } from '../services/diagnostic-service';
import { db } from '../database/database';
import { showToast } from '../ui/feedback';

export async function initializeDiagnosticsPage() {
    const page = document.querySelector('[data-diagnostics-page]'); if (!page) return;
    const toast = page.querySelector('[data-diagnostics-toast]'); const notify = (message, variant = 'success') => showToast(toast, message, variant); let report = null;
    const saved = (await db.settings.get('offline_acceptance'))?.value || { checks: {}, notes: '', updated_at: null };
    const checklist = page.querySelector('[data-acceptance-list]');
    for (const [id, label] of ACCEPTANCE_ITEMS) { const row = document.createElement('label'); row.className = 'flex cursor-pointer items-start gap-3 rounded-xl border border-gray-200 p-3 dark:border-gray-700'; const input = document.createElement('input'); input.type = 'checkbox'; input.dataset.acceptanceId = id; input.checked = Boolean(saved.checks[id]); input.className = 'mt-0.5 h-4 w-4 accent-brand-500'; const text = document.createElement('span'); text.className = 'text-sm text-gray-700 dark:text-gray-300'; text.textContent = label; row.append(input, text); checklist.append(row); }
    page.querySelector('[data-acceptance-notes]').value = saved.notes || '';
    const saveChecklist = async () => { const checks = {}; page.querySelectorAll('[data-acceptance-id]').forEach((input) => { checks[input.dataset.acceptanceId] = input.checked; }); await db.settings.put({ key: 'offline_acceptance', value: { checks, notes: page.querySelector('[data-acceptance-notes]').value.trim(), browser: navigator.userAgent, updated_at: new Date().toISOString() }, updated_at: new Date().toISOString() }); const done = Object.values(checks).filter(Boolean).length; page.querySelector('[data-manual-progress]').textContent = `${done}/${ACCEPTANCE_ITEMS.length} selesai`; notify('Checklist acceptance disimpan.'); };
    page.querySelector('[data-save-acceptance]').addEventListener('click', saveChecklist);
    page.querySelector('[data-manual-progress]').textContent = `${Object.values(saved.checks).filter(Boolean).length}/${ACCEPTANCE_ITEMS.length} selesai`;
    const render = (diagnostic) => { const list = page.querySelector('[data-diagnostic-results]'); list.replaceChildren(); const styles = { pass: ['bg-success-50 text-success-700', '✓'], warn: ['bg-warning-50 text-warning-700', '!'], fail: ['bg-error-50 text-error-700', '×'] }; for (const item of diagnostic.results) { const row = document.createElement('article'); row.className = 'flex gap-3 border-b border-gray-100 py-4 last:border-0 dark:border-gray-800'; const badge = document.createElement('span'); badge.className = `flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${styles[item.status][0]}`; badge.textContent = styles[item.status][1]; const copy = document.createElement('div'); const title = document.createElement('p'); title.className = 'text-sm font-semibold text-gray-900 dark:text-white'; title.textContent = item.label; const detail = document.createElement('p'); detail.className = 'mt-0.5 text-xs text-gray-500'; detail.textContent = item.detail; copy.append(title, detail); row.append(badge, copy); list.append(row); } page.querySelector('[data-diagnostic-summary]').textContent = diagnostic.summary.ready ? `Siap diuji offline • ${diagnostic.summary.passed} lulus, ${diagnostic.summary.warnings} peringatan` : `Belum siap • ${diagnostic.summary.failed} gagal, ${diagnostic.summary.warnings} peringatan`; page.querySelector('[data-export-diagnostic]').disabled = false; };
    page.querySelector('[data-run-diagnostics]').addEventListener('click', async () => { const button = page.querySelector('[data-run-diagnostics]'); button.disabled = true; try { report = await runDiagnostics(); render(report); notify('Diagnostic selesai dijalankan.'); } catch (error) { notify(error.message, 'error'); } finally { button.disabled = false; } });
    page.querySelector('[data-export-diagnostic]').addEventListener('click', () => { if (!report) return; const safeReport = { ...report, userAgent: navigator.userAgent, url: location.origin }; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(safeReport, null, 2)], { type: 'application/json' })); link.download = `rumahkas-diagnostic-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); });
}
