import $ from 'jquery';
import { db } from '../database/database';
import { initializeDatabase } from '../services/database-service';
import { HabitService, HabitValidationError } from '../services/habit-service';
import { habitInsight } from '../services/insight-service';
import { confirmDialog, hideModal, showModal, showToast } from '../ui/feedback';

const months = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const escapeHtml = (value) => $('<div>').text(value ?? '').html();
const templates = {
    water: { name: 'Minum 8 gelas air', icon: '💧', tracking_type: 'count', target_value: 8, unit: 'gelas', color: '#0ea5e9', selected_days: [0,1,2,3,4,5,6] },
    exercise: { name: 'Olahraga 20 menit', icon: '🏃', tracking_type: 'duration', target_value: 20, unit: 'menit', color: '#f97316', selected_days: [1,3,5] },
    read: { name: 'Membaca 15 menit', icon: '📖', tracking_type: 'duration', target_value: 15, unit: 'menit', color: '#8b5cf6', selected_days: [0,1,2,3,4,5,6] },
    sleep: { name: 'Tidur sebelum pukul 22.30', icon: '🌙', tracking_type: 'boolean', target_value: 1, unit: 'kali', color: '#6366f1', selected_days: [0,1,2,3,4,5,6] },
};

export async function initializeHabitPage() {
    await initializeDatabase(); const service = new HabitService(db); const $page = $('[data-habit-page]'); const $modal = $('[data-habit-modal]'); const $form = $('#habit-form'); const now = new Date(); const year = now.getFullYear(); let activeMonth = now.getMonth() + 1;
    const notify = (message, variant = 'success') => showToast($('[data-habit-toast]'), message, variant);
    const renderMonths = () => { $('[data-month-list]').html(months.map((name, index) => `<button data-month="${index + 1}" class="shrink-0 rounded-xl px-3.5 py-2.5 text-xs font-semibold ${activeMonth === index + 1 ? 'bg-brand-600 text-white shadow-theme-xs' : 'bg-gray-50 text-gray-500 hover:bg-brand-50 dark:bg-white/[0.04]'}">${name.slice(0, 3)}</button>`).join('')); $('[data-month-list] [data-month].bg-brand-600'); };
    const render = async () => { renderMonths(); const data = await service.month(year, activeMonth); const insight = habitInsight(data); $('[data-habit-insight-icon]').text(insight.icon); $('[data-habit-insight-eyebrow]').text(insight.eyebrow); $('[data-habit-insight-title]').text(insight.title); $('[data-habit-insight-detail]').text(insight.detail); $('[data-grid-title]').text(`${months[activeMonth - 1]} ${year}`);
        if (!data.rows.length) { $('[data-habit-grid]').html('<div class="px-6 py-14 text-center"><p class="text-3xl">◎</p><h3 class="mt-3 font-semibold text-gray-900 dark:text-white">Belum ada habit</h3><p class="mt-1 text-sm text-gray-500">Buat kebiasaan pertama untuk mulai melacak konsistensi.</p><button data-empty-add class="mt-5 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">+ Buat habit</button></div>'); return; }
        const weekdayHeader = ['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map((name) => `<span class="py-1 text-center text-[9px] font-semibold uppercase text-gray-400">${name}</span>`).join(''); const firstOffset = (new Date(year, activeMonth - 1, 1).getDay() + 6) % 7;
        const cards = data.rows.map((habit) => { const blanks = Array.from({ length: firstOffset }, () => '<span></span>').join(''); const days = habit.days.map((day) => { const today = day.date === new Date().toLocaleDateString('en-CA'); return `<div class="flex min-h-11 flex-col items-center justify-center rounded-lg ${today ? 'bg-brand-50 dark:bg-brand-500/10' : ''}"><span class="mb-1 text-[9px] font-medium ${today ? 'text-brand-600' : 'text-gray-400'}">${day.day}</span>${day.scheduled ? `<button data-check-date="${day.date}" ${day.future ? 'disabled' : ''} aria-label="${habit.name} tanggal ${day.day}" class="grid h-6 w-6 place-items-center rounded-md border text-[10px] transition ${day.completed ? 'border-transparent text-white' : day.future ? 'cursor-not-allowed border-gray-100 text-transparent dark:border-gray-800' : 'border-gray-300 text-transparent hover:border-brand-400 dark:border-gray-700'}" ${day.completed ? `style="background:${habit.color}"` : ''}>✓</button>` : '<span class="h-1.5 w-1.5 rounded-full bg-gray-200 dark:bg-gray-700"></span>'}</div>`; }).join(''); return `<article data-habit-id="${habit.id}" class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-lg" style="background:${habit.color}18;color:${habit.color}">${escapeHtml(habit.icon)}</span><div class="min-w-0 flex-1"><div class="flex items-center justify-between gap-2"><h4 class="truncate text-sm font-semibold text-gray-900 dark:text-white">${escapeHtml(habit.name)}</h4><span class="text-xs font-bold" style="color:${habit.color}">${habit.percentage}%</span></div><p class="mt-0.5 text-[10px] text-gray-400">${habit.completed_count}/${habit.scheduled_count} selesai · 🔥 ${habit.streak}</p></div><button data-edit-habit class="px-1 text-lg text-gray-400">⋯</button></div><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-gray-100 dark:bg-white/[0.06]"><div class="h-full rounded-full" style="width:${habit.percentage}%;background:${habit.color}"></div></div><div data-row-actions class="mt-2 hidden justify-end gap-3 text-[10px]"><button data-habit-action="edit" class="font-semibold text-brand-600">Edit</button><button data-habit-action="delete" class="font-semibold text-error-600">Hapus</button></div><div class="mt-3 grid grid-cols-7">${weekdayHeader}${blanks}${days}</div></article>`; }).join('');
        $('[data-habit-grid]').html(`<div class="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">${cards}</div>`);
    };
    const fillHabitForm = (item = {}) => { $form.find('[name=name]').val(item.name || ''); $form.find('[name=icon]').val(item.icon || '✓'); $form.find('[name=tracking_type]').val(item.tracking_type || 'boolean').trigger('change'); $form.find('[name=target_value]').val(item.target_value || 1); $form.find('[name=unit]').val(item.unit || 'kali'); $form.find('[name=color]').val(item.color || '#8b5cf6'); $form.find('[name="selected_days[]"]').each(function () { $(this).prop('checked', !item.selected_days || item.selected_days.includes(Number(this.value))); }); };
    const openHabit = (item = null) => { $form[0].reset(); $form.find('[name=id]').val(item?.id || ''); fillHabitForm(item || {}); $('[data-habit-template]').removeClass('border-brand-500 bg-brand-50 ring-1 ring-brand-500 dark:bg-brand-500/10'); $('[data-habit-templates]').toggleClass('hidden', Boolean(item)); $('[data-habit-modal-title]').text(item ? 'Edit habit' : 'Habit baru'); $('[data-habit-error]').addClass('hidden'); showModal($modal); };
    $page.on('click', '[data-month]', function () { activeMonth = Number($(this).data('month')); render(); }); $('[data-add-habit]').on('click', () => openHabit()); $page.on('click', '[data-empty-add]', () => openHabit()); $page.on('click', '[data-edit-habit]', function () { $(this).closest('[data-habit-id]').find('[data-row-actions]').toggleClass('hidden flex'); });
    $modal.on('click', '[data-habit-template]', function () { const template = templates[$(this).data('habit-template')]; if (!template) return; fillHabitForm(template); $('[data-habit-template]').removeClass('border-brand-500 bg-brand-50 ring-1 ring-brand-500 dark:bg-brand-500/10'); $(this).addClass('border-brand-500 bg-brand-50 ring-1 ring-brand-500 dark:bg-brand-500/10'); $form.find('[name=name]').trigger('focus'); });
    $page.on('click', '[data-check-date]', async function () { const id = $(this).closest('[data-habit-id]').data('habit-id'); await service.toggle(id, $(this).data('check-date')); await render(); });
    $page.on('click', '[data-habit-action]', async function () { const id = $(this).closest('[data-habit-id]').data('habit-id'); const action = $(this).data('habit-action'); const habit = await service.find(id); if (action === 'edit') return openHabit(habit); if (action === 'delete' && await confirmDialog({ title: `Hapus “${habit.name}”?`, message: 'Habit dan seluruh checklist riwayatnya akan dihapus permanen.', confirmText: 'Hapus habit' })) { await service.delete(id); notify('Habit dihapus.'); await render(); } });
    $('[data-close-habit]').on('click', () => hideModal($modal)); $modal.on('click', function (event) { if (event.target === this) hideModal($modal); }); $form.find('[name=tracking_type]').on('change', function () { const value = this.value; $('[data-habit-target-fields]').toggleClass('hidden', value === 'boolean'); $('[data-habit-unit-wrap]').toggleClass('hidden', value === 'duration'); });
    $form.on('submit', async function (event) { event.preventDefault(); const formData = new FormData(this); const data = Object.fromEntries(formData); data.selected_days = formData.getAll('selected_days[]'); try { data.id ? await service.update(data.id, data) : await service.create(data); hideModal($modal); notify(data.id ? 'Habit diperbarui.' : 'Habit ditambahkan.'); await render(); } catch (error) { $('[data-habit-error]').removeClass('hidden').text(error instanceof HabitValidationError ? error.message : 'Habit gagal disimpan.'); } });
    await render();
}
