import { downloadRecoverySnapshot, pendingUpgrade, restoreRecoverySnapshot } from '../services/recovery-service';
import { confirmDialog } from '../ui/feedback';

export async function showRecoveryScreen(failure) {
    const migration = await pendingUpgrade().catch(() => null); const gate = document.querySelector('[data-auth-gate]'); const shell = document.querySelector('[data-app-shell]'); gate?.remove(); shell?.classList.add('hidden');
    const screen = document.createElement('main'); screen.className = 'fixed inset-0 z-[100000] overflow-y-auto bg-gray-50 p-4 dark:bg-gray-950';
    screen.innerHTML = '<section class="mx-auto mt-[10vh] max-w-xl rounded-2xl border border-error-200 bg-white p-6 shadow-theme-xl dark:border-error-800 dark:bg-gray-900 sm:p-8"><span class="flex h-12 w-12 items-center justify-center rounded-xl bg-error-50 text-xl font-bold text-error-600">!</span><h1 class="mt-5 text-2xl font-bold text-gray-900 dark:text-white">Update belum dapat diselesaikan</h1><p class="mt-2 text-sm leading-6 text-gray-500">Data tidak akan dihapus otomatis. Gunakan snapshot recovery atau unduh salinannya sebelum mencoba lagi.</p><pre data-recovery-error class="mt-4 whitespace-pre-wrap rounded-xl bg-gray-50 p-4 text-xs text-error-700 dark:bg-gray-800"></pre><div class="mt-6 grid gap-3 sm:grid-cols-2"><button data-retry class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Coba lagi</button><button data-download class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium dark:border-gray-700">Download snapshot</button><button data-restore class="rounded-lg border border-warning-300 px-4 py-2.5 text-sm font-medium text-warning-700 sm:col-span-2">Pulihkan snapshot sebelum update</button></div><p data-recovery-status class="mt-4 text-sm text-gray-500"></p></section>';
    screen.querySelector('[data-recovery-error]').textContent = failure?.message || migration?.error || 'Migration atau integrity check gagal.';
    screen.querySelector('[data-retry]').onclick = () => location.reload();
    screen.querySelector('[data-download]').onclick = async () => { try { const content = await downloadRecoverySnapshot(migration); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'application/json' })); link.download = `rumahkas-recovery-${migration?.source_version || 'previous'}.json`; link.click(); URL.revokeObjectURL(link.href); } catch (error) { screen.querySelector('[data-recovery-status]').textContent = error.message; } };
    screen.querySelector('[data-restore]').onclick = async () => { if (!await confirmDialog({ title: 'Pulihkan snapshot sebelumnya?', message: 'Database lokal akan dikembalikan ke kondisi sebelum update yang gagal.', confirmText: 'Pulihkan snapshot', variant: 'primary' })) return; try { await restoreRecoverySnapshot(migration); screen.querySelector('[data-recovery-status]').textContent = 'Snapshot berhasil dipulihkan. Memuat ulang…'; setTimeout(() => location.reload(), 900); } catch (error) { screen.querySelector('[data-recovery-status]').textContent = error.message; } };
    document.body.append(screen);
}
