import $ from 'jquery';
import flatpickr from 'flatpickr';
import { Indonesian } from 'flatpickr/dist/l10n/id.js';
import 'flatpickr/dist/flatpickr.min.css';
import { db } from '../database/database';
import { initializeDatabase } from '../services/database-service';
import { SavingGoalService, SavingGoalValidationError } from '../services/saving-goal-service';
import { bindMoneyInput, getMoneyValue, setMoneyValue } from '../ui/money-input';
import { confirmDialog, hideModal, showModal, showToast } from '../ui/feedback';

const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const escapeHtml = (value) => $('<div>').text(value ?? '').html();

export async function initializeSavingGoalPage() {
    await initializeDatabase();
    const service = new SavingGoalService(db); const $page = $('[data-saving-goal-page]');
    const $modal = $('[data-goal-modal]'); const $form = $('#saving-goal-form'); const $amount = $form.find('[name="target_amount"]'); const $saved = $form.find('[name="saved_amount"]');
    const $fundModal = $('[data-fund-modal]'); const $fundForm = $('#goal-fund-form'); const $fundAmount = $fundForm.find('[name="contribution"]');
    bindMoneyInput($amount); bindMoneyInput($saved); bindMoneyInput($fundAmount);
    flatpickr($form.find('[name="target_date"]')[0], { locale: Indonesian, dateFormat: 'Y-m-d', altInput: true, altFormat: 'j F Y', minDate: 'today', disableMobile: true });
    const notify = (message, variant = 'success') => showToast($('[data-goal-toast]'), message, variant);

    const render = async () => {
        const goals = await service.list(); const active = goals.filter((goal) => goal.status === 'active');
        $('[data-goal-count]').text(goals.length); $('[data-goal-saved]').text(idr.format(goals.reduce((sum, goal) => sum + goal.saved_amount, 0))); $('[data-goal-remaining]').text(idr.format(active.reduce((sum, goal) => sum + goal.remaining, 0)));
        $('[data-goal-list]').html(goals.length ? goals.map((goal) => `<article data-goal-id="${goal.id}" class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-start justify-between gap-3"><div><span class="mb-3 flex h-11 w-11 items-center justify-center rounded-xl ${goal.status === 'completed' ? 'bg-success-50 text-success-600' : 'bg-brand-50 text-brand-600'}">${goal.status === 'completed' ? '✓' : '◎'}</span><h3 class="font-semibold text-gray-900 dark:text-white">${escapeHtml(goal.name)}</h3><p class="mt-1 text-xs text-gray-500">${goal.target_date ? `Target ${new Date(`${goal.target_date}T00:00:00`).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}` : 'Tanpa batas waktu'}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-medium ${goal.status === 'completed' ? 'bg-success-50 text-success-700' : 'bg-brand-50 text-brand-700'}">${goal.status === 'completed' ? 'Tercapai' : `${Math.round(goal.percentage)}%`}</span></div><div class="mt-5 flex justify-between text-sm"><span class="font-semibold text-gray-900 dark:text-white">${idr.format(goal.saved_amount)}</span><span class="text-gray-500">dari ${idr.format(goal.target_amount)}</span></div><div class="mt-2 h-2.5 overflow-hidden rounded-full bg-gray-100 dark:bg-white/[0.06]"><div class="h-full rounded-full ${goal.status === 'completed' ? 'bg-success-500' : 'bg-brand-500'} transition-all duration-500" style="width:${goal.percentage}%"></div></div><div class="mt-4 flex items-center justify-between border-t border-gray-100 pt-4 dark:border-gray-800"><span class="text-xs text-gray-500">${goal.status === 'completed' ? 'Target telah tercapai' : `Kurang ${idr.format(goal.remaining)}`}</span><div class="flex gap-1"><button data-action="fund" class="rounded-lg px-2.5 py-2 text-xs font-semibold text-brand-600 hover:bg-brand-50">Atur dana</button><button data-action="edit" class="rounded-lg p-2 text-gray-500 hover:bg-gray-100">✎</button><button data-action="delete" class="rounded-lg p-2 text-gray-500 hover:bg-error-50 hover:text-error-600">×</button></div></div></article>`).join('') : '<div class="col-span-full rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-16 text-center dark:border-gray-700 dark:bg-white/[0.03]"><p class="text-3xl">◎</p><p class="mt-3 font-semibold text-gray-900 dark:text-white">Belum ada target tabungan</p><p class="mt-1 text-sm text-gray-500">Mulai dari dana darurat, liburan, atau kebutuhan keluarga.</p><button data-add-goal class="mt-5 rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Buat target pertama</button></div>');
    };

    const openGoal = async (goal = null) => { $form[0].reset(); $form.find('[name="id"]').val(goal?.id || ''); $form.find('[name="name"]').val(goal?.name || ''); setMoneyValue($amount, goal?.target_amount || ''); setMoneyValue($saved, goal?.saved_amount || ''); $form.find('[name="target_date"]').val(goal?.target_date || ''); $form.find('[name="notes"]').val(goal?.notes || ''); $('[data-goal-modal-title]').text(goal ? 'Edit target tabungan' : 'Target tabungan baru'); $('[data-goal-error]').addClass('hidden'); showModal($modal); };
    $page.on('click', '[data-add-goal]', () => openGoal()); $('[data-close-goal-modal]').on('click', () => hideModal($modal)); $('[data-close-fund-modal]').on('click', () => hideModal($fundModal));
    $page.on('click', '[data-goal-id] [data-action]', async function () { const id = $(this).closest('[data-goal-id]').data('goal-id'); const action = $(this).data('action'); const goal = await service.find(id); if (action === 'edit') openGoal(goal); if (action === 'fund') { $fundForm[0].reset(); $fundForm.find('[name="id"]').val(id); $('[data-fund-goal-name]').text(goal.name); setMoneyValue($fundAmount, ''); showModal($fundModal); } if (action === 'delete' && await confirmDialog({ title: `Hapus target “${goal.name}”?`, message: 'Target dan catatan progres dananya akan dihapus permanen.', confirmText: 'Hapus target' })) { await service.delete(id); notify('Target tabungan dihapus.'); render(); } });
    $form.on('submit', async function (event) { event.preventDefault(); const values = Object.fromEntries(new FormData(this)); values.target_amount = getMoneyValue($amount); values.saved_amount = getMoneyValue($saved); const $submit = $form.find('[type="submit"]').prop('disabled', true); try { values.id ? await service.update(values.id, values) : await service.create(values); hideModal($modal); notify(values.id ? 'Target diperbarui.' : 'Target tabungan dibuat.'); await render(); } catch (error) { $('[data-goal-error]').removeClass('hidden').text(error instanceof SavingGoalValidationError ? error.message : 'Target gagal disimpan.'); } finally { $submit.prop('disabled', false); } });
    $fundForm.on('submit', async function (event) { event.preventDefault(); const amount = getMoneyValue($fundAmount); const direction = $(this).find('[name="direction"]').val() === 'subtract' ? -1 : 1; try { await service.contribute($(this).find('[name="id"]').val(), amount * direction); hideModal($fundModal); notify('Dana target diperbarui.'); await render(); } catch (error) { notify(error.message, 'error'); } });
    $modal.add($fundModal).on('click', function (event) { if (event.target === this) hideModal($(this)); }); await render();
}
