@extends('layouts.app')

@section('content')
<div data-planner-page class="space-y-5">
    <section class="flex items-end justify-between gap-4"><div><p class="mb-1 text-sm font-medium text-brand-600">Rutinitas sehari-hari</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Planner</h2><p data-planner-date-label class="mt-1 text-sm text-gray-500"></p></div><button data-planner-add class="min-h-11 rounded-xl bg-brand-500 px-4 text-sm font-semibold text-white shadow-theme-xs">+ Tambah</button></section>
    <section data-task-panel class="grid items-start gap-5 lg:grid-cols-[minmax(330px,0.85fr)_minmax(480px,1.35fr)]">
        <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white lg:sticky lg:top-24 dark:border-gray-800 dark:bg-white/[0.03]"><header class="flex items-center justify-between border-b border-gray-100 px-4 py-3 dark:border-gray-800"><button data-calendar-prev type="button" class="grid h-9 w-9 place-items-center rounded-xl text-xl text-gray-500 hover:bg-gray-100 dark:hover:bg-white/[0.06]">‹</button><div class="text-center"><h3 data-calendar-title class="font-semibold text-gray-900 dark:text-white"></h3><button data-calendar-today type="button" class="mt-0.5 text-xs font-semibold text-brand-600">Kembali ke hari ini</button></div><button data-calendar-next type="button" class="grid h-9 w-9 place-items-center rounded-xl text-xl text-gray-500 hover:bg-gray-100 dark:hover:bg-white/[0.06]">›</button></header><div class="grid grid-cols-7 border-b border-gray-100 px-2 py-2 text-center text-[10px] font-semibold uppercase text-gray-400 dark:border-gray-800"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div><div data-month-calendar class="grid grid-cols-7 p-2"></div><footer class="flex items-center gap-4 border-t border-gray-100 px-4 py-3 text-[11px] text-gray-500 dark:border-gray-800"><span class="flex items-center gap-1.5"><i class="h-1.5 w-1.5 rounded-full bg-brand-400"></i>Belum selesai</span><span class="flex items-center gap-1.5"><i class="h-1.5 w-1.5 rounded-full bg-success-500"></i>Selesai</span></footer></div>
        <div class="min-w-0 space-y-4"><section class="relative overflow-hidden rounded-2xl border border-brand-100 bg-gradient-to-r from-brand-50 to-blue-light-50 px-4 py-4 dark:border-brand-500/20 dark:from-brand-500/10 dark:to-blue-light-500/10"><div class="relative z-10 flex items-start gap-3"><span data-planner-insight-icon class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-lg text-brand-600 shadow-theme-xs dark:bg-white/10">✦</span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-3"><div><p data-planner-insight-eyebrow class="text-[11px] font-bold uppercase tracking-wider text-brand-600">Insight harian</p><h3 data-planner-insight-title class="mt-1 text-sm font-semibold text-gray-900 sm:text-base dark:text-white">Mulai dengan satu langkah kecil.</h3></div><button data-add-period="morning" class="shrink-0 rounded-xl bg-white px-3 py-2 text-xs font-semibold text-brand-600 shadow-theme-xs dark:bg-white/10">+ Aktivitas</button></div><p data-planner-insight-detail class="mt-1 text-xs leading-5 text-gray-500 dark:text-gray-400">Pilih satu aktivitas yang paling berarti buatmu hari ini.</p></div></div><div class="absolute -right-8 -top-10 h-28 w-28 rounded-full bg-brand-200/30 blur-2xl"></div></section><section class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.03]"><div class="mb-3 flex items-center justify-between"><div><h3 class="text-sm font-semibold text-gray-900 dark:text-white">Template cepat</h3><p class="text-xs text-gray-500">Pilih untuk mengisi aktivitas otomatis</p></div></div><div class="flex gap-2 overflow-x-auto pb-1"><button data-task-template data-title="Olahraga 20 menit" data-period="morning" data-time="06:30" class="whitespace-nowrap rounded-full bg-orange-50 px-3 py-2 text-xs font-medium text-orange-700">🏃 Olahraga</button><button data-task-template data-title="Belanja kebutuhan rumah" data-period="afternoon" class="whitespace-nowrap rounded-full bg-blue-light-50 px-3 py-2 text-xs font-medium text-blue-light-700">🛒 Belanja</button><button data-task-template data-title="Bersih-bersih rumah" data-period="morning" class="whitespace-nowrap rounded-full bg-success-50 px-3 py-2 text-xs font-medium text-success-700">🧹 Bersih-bersih</button><button data-task-template data-title="Belajar atau membaca" data-period="evening" data-time="20:00" class="whitespace-nowrap rounded-full bg-brand-50 px-3 py-2 text-xs font-medium text-brand-700">📖 Belajar</button><button data-task-template data-title="Waktu untuk diri sendiri" data-period="evening" class="whitespace-nowrap rounded-full bg-pink-50 px-3 py-2 text-xs font-medium text-pink-700">🌿 Me time</button><button data-task-template data-title="Review keuangan hari ini" data-period="evening" class="whitespace-nowrap rounded-full bg-brand-50 px-3 py-2 text-xs font-medium text-brand-700">💰 Review keuangan</button></div></section><div data-task-groups class="space-y-4"></div></div>
    </section>

</div>

<div data-task-modal class="app-modal fixed inset-0 z-99999 hidden items-end justify-center bg-gray-950/50 p-0 sm:items-center sm:p-4"><div class="app-modal-panel w-full max-w-md rounded-t-3xl bg-white p-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] sm:rounded-2xl sm:p-6 dark:bg-gray-900"><div class="mx-auto mb-4 h-1 w-10 rounded-full bg-gray-300 sm:hidden"></div><div class="mb-5 flex items-center justify-between"><h3 data-task-modal-title class="text-xl font-bold">Aktivitas baru</h3><button data-close-task type="button" class="p-2 text-xl text-gray-400">×</button></div><form id="planner-task-form" class="space-y-4"><input type="hidden" name="id"><label class="block text-sm font-medium">Aktivitas<input name="title" required maxlength="100" placeholder="Contoh: Olahraga 15 menit" class="mt-1.5 h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><div class="grid grid-cols-2 gap-3"><label class="block text-sm font-medium">Tanggal<input name="task_date" type="date" required class="mt-1.5 h-11 w-full rounded-xl border border-gray-300 bg-transparent px-3 dark:border-gray-700"></label><label class="block text-sm font-medium">Jam <span class="font-normal text-gray-400">(opsional)</span><input name="time" type="time" class="mt-1.5 h-11 w-full rounded-xl border border-gray-300 bg-transparent px-3 dark:border-gray-700"></label></div><div class="grid grid-cols-2 gap-3"><label class="block text-sm font-medium">Bagian hari<select name="day_period" class="mt-1.5 h-11 w-full rounded-xl border border-gray-300 bg-transparent px-3 dark:border-gray-700 dark:bg-gray-900"><option value="morning">Pagi</option><option value="afternoon">Siang</option><option value="evening">Malam</option></select></label><label class="block text-sm font-medium">Prioritas<select name="priority" class="mt-1.5 h-11 w-full rounded-xl border border-gray-300 bg-transparent px-3 dark:border-gray-700 dark:bg-gray-900"><option value="normal">Normal</option><option value="high">Penting</option><option value="low">Santai</option></select></label></div><label class="block text-sm font-medium">Catatan <span class="font-normal text-gray-400">(opsional)</span><textarea name="notes" maxlength="500" rows="3" class="mt-1.5 w-full rounded-xl border border-gray-300 bg-transparent p-3 dark:border-gray-700"></textarea></label><p data-task-error class="hidden rounded-xl bg-error-50 p-3 text-sm text-error-700"></p><div class="grid grid-cols-2 gap-3"><button data-close-task type="button" class="min-h-11 rounded-xl border border-gray-300 text-sm font-medium">Batal</button><button class="min-h-11 rounded-xl bg-brand-500 text-sm font-semibold text-white">Simpan</button></div></form></div></div>

<div data-planner-toast class="app-toast hidden"></div>
@endsection
