@extends('layouts.app')

@section('content')
<div data-settings-page class="space-y-6">
    <section><p class="mb-1 text-sm font-medium text-brand-600">Preferensi lokal</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Pengaturan</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Atur profil keluarga, tampilan, backup, dan keamanan perangkat ini.</p></section>

    <div class="grid gap-6 xl:grid-cols-3">
        <section class="space-y-6 xl:col-span-2">
            <article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] sm:p-6"><div class="mb-6"><h3 class="font-semibold text-gray-900 dark:text-white">Profil keuangan</h3><p class="mt-1 text-sm text-gray-500">Digunakan sebagai identitas buku keuangan lokal.</p></div><form data-profile-form class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 sm:col-span-2">Nama keluarga atau profil<input name="name" required minlength="2" maxlength="80" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 outline-none focus:border-brand-500 dark:border-gray-700"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-300">Mata uang<input value="Rupiah Indonesia (IDR)" disabled class="mt-1.5 h-11 w-full rounded-lg border border-gray-200 bg-gray-50 px-4 text-gray-500 dark:border-gray-800 dark:bg-gray-800"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-300">Awal periode bulanan<select name="month_start_day" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700 dark:bg-gray-900">@for($day=1;$day<=28;$day++)<option value="{{ $day }}">Tanggal {{ $day }}</option>@endfor</select></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 sm:col-span-2">Pengingat backup<select name="backup_reminder_days" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700 dark:bg-gray-900"><option value="7">Setiap 7 hari</option><option value="14">Setiap 14 hari</option><option value="30">Setiap 30 hari</option><option value="0">Jangan ingatkan</option></select></label><div class="sm:col-span-2 sm:text-right"><button class="rounded-lg bg-brand-500 px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-600 disabled:opacity-50">Simpan pengaturan</button></div></form></article>

            <article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] sm:p-6"><div class="mb-6"><h3 class="font-semibold text-gray-900 dark:text-white">Ganti PIN offline</h3><p class="mt-1 text-sm text-gray-500">PIN hanya diganti pada perangkat ini dan harus terdiri dari 6 angka.</p></div><form data-pin-change-form class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium text-gray-700 dark:text-gray-300 sm:col-span-2">PIN saat ini<input name="current_pin" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="current-password" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 tracking-[.35em] outline-none focus:border-brand-500 dark:border-gray-700"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-300">PIN baru<input name="new_pin" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="new-password" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 tracking-[.35em] outline-none focus:border-brand-500 dark:border-gray-700"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-300">Konfirmasi PIN baru<input name="new_pin_confirmation" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="new-password" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 tracking-[.35em] outline-none focus:border-brand-500 dark:border-gray-700"></label><div class="sm:col-span-2 sm:text-right"><button class="rounded-lg border border-brand-500 px-5 py-2.5 text-sm font-semibold text-brand-600 hover:bg-brand-50 dark:hover:bg-brand-500/10">Ganti PIN</button></div></form></article>
        </section>

        <aside class="space-y-6">
            <article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-900 dark:text-white">Akun berlisensi</h3><div class="mt-4 flex h-12 w-12 items-center justify-center rounded-full bg-brand-50 font-bold text-brand-600 dark:bg-brand-500/10">✓</div><p data-account-name class="mt-4 font-semibold">-</p><p data-account-email class="text-sm text-gray-500">-</p><dl class="mt-5 space-y-3 border-t border-gray-100 pt-4 text-sm dark:border-gray-800"><div class="flex justify-between gap-3"><dt class="text-gray-500">Lisensi</dt><dd data-license-product class="text-right font-medium">-</dd></div><div class="flex justify-between gap-3"><dt class="text-gray-500">Status offline</dt><dd data-offline-ready class="text-right font-medium text-gray-500">Memeriksa…</dd></div><div class="flex justify-between gap-3"><dt class="text-gray-500">Versi aplikasi</dt><dd data-app-version class="text-right font-medium">-</dd></div><div class="flex justify-between gap-3"><dt class="text-gray-500">Backup terakhir</dt><dd data-last-backup class="text-right font-medium">-</dd></div></dl><div class="mt-5 grid gap-2"><button data-check-update type="button" class="rounded-lg border border-brand-300 px-4 py-2.5 text-sm font-medium text-brand-700 disabled:opacity-50">Periksa update</button><a href="/backup" class="block rounded-lg bg-gray-100 px-4 py-2.5 text-center text-sm font-medium text-gray-700 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-300">Buat backup sekarang</a></div></article>
            <article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-900 dark:text-white">Tema tampilan</h3><div class="mt-4 grid grid-cols-2 gap-3"><button data-theme-choice="light" type="button" class="rounded-xl border border-gray-200 bg-gray-50 p-4 text-sm font-medium hover:border-brand-500 dark:border-gray-700">☀️<span class="mt-2 block">Terang</span></button><button data-theme-choice="dark" type="button" class="rounded-xl border border-gray-700 bg-gray-900 p-4 text-sm font-medium text-white hover:border-brand-500">🌙<span class="mt-2 block">Gelap</span></button></div></article>
        </aside>
    </div>
    <section class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-sm font-medium text-brand-600">Perawatan lokal</p><h3 class="mt-1 text-lg font-semibold text-gray-900 dark:text-white">Database Health & Storage</h3><p class="mt-1 text-sm text-gray-500">Periksa konsistensi data dan kapasitas penyimpanan perangkat.</p></div><button data-run-health type="button" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Jalankan pemeriksaan</button></div>
        <div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p class="text-xs text-gray-500">Status database</p><p data-health-status class="mt-1 font-semibold">Belum diperiksa</p></div><div class="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p class="text-xs text-gray-500">Penggunaan storage</p><p data-storage-usage class="mt-1 font-semibold">Menghitung…</p></div><div class="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p class="text-xs text-gray-500">Persistent storage</p><p data-storage-persistent class="mt-1 font-semibold">-</p></div><div class="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p class="text-xs text-gray-500">Data lokal</p><p data-local-count class="mt-1 font-semibold">-</p></div></div>
        <div data-health-results class="mt-4 hidden rounded-xl border border-gray-200 p-4 text-sm dark:border-gray-700"></div>
        <div class="mt-6 flex flex-col gap-3 border-t border-gray-100 pt-5 sm:flex-row dark:border-gray-800"><button data-clean-audit type="button" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium dark:border-gray-700">Bersihkan catatan lama</button><button data-reset-data type="button" class="rounded-lg border border-error-200 px-4 py-2.5 text-sm font-medium text-error-600 hover:bg-error-50 dark:border-error-800">Hapus seluruh data finansial</button></div>
    </section>
    <div data-settings-toast class="app-toast hidden"></div>
</div>
@endsection
