@extends('layouts.app')

@section('content')
<div data-budget-page class="space-y-6">
    <section class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-sm font-medium text-brand-600">Kontrol pengeluaran</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Budget Bulanan</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Tetapkan batas pengeluaran setiap kategori.</p></div><div class="flex flex-col gap-3 sm:flex-row"><div class="relative"><span class="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-gray-400">▦</span><input data-budget-period type="text" readonly aria-label="Pilih periode budget" class="h-11 w-full cursor-pointer rounded-lg border border-gray-300 bg-white py-2 pl-10 pr-4 text-sm font-medium text-gray-700 outline-none hover:border-brand-400 focus:border-brand-500 sm:w-48 dark:border-gray-700 dark:bg-gray-900 dark:text-white"></div><button data-add-budget class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-600">+ Tambah budget</button></div></section>
    <section class="grid grid-cols-1 gap-4 sm:grid-cols-3"><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Total budget</p><p data-budget-total class="mt-2 text-xl font-bold text-gray-900 dark:text-white">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Terpakai</p><p data-budget-spent class="mt-2 text-xl font-bold text-error-600">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Sisa budget</p><p data-budget-remaining class="mt-2 text-xl font-bold text-success-600">Rp0</p></article></section>
    <section data-budget-list class="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3"><p class="col-span-full py-10 text-center text-sm text-gray-500">Memuat budget…</p></section>
</div>

<div data-budget-modal class="app-modal fixed inset-0 z-99999 hidden items-center justify-center overflow-y-auto bg-gray-950/50 p-4" role="dialog" aria-modal="true" aria-hidden="true"><div class="app-modal-panel my-6 w-full max-w-md rounded-2xl bg-white p-6 shadow-theme-xl dark:bg-gray-900"><div class="mb-5 flex items-center justify-between"><h2 data-budget-modal-title class="text-xl font-bold text-gray-900 dark:text-white">Tambah budget</h2><button data-close-budget-modal type="button" class="rounded-lg p-2 text-xl text-gray-400 hover:bg-gray-100">×</button></div><form id="budget-form" class="space-y-4"><input type="hidden" name="id"><div><label class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Kategori pengeluaran</label><select name="category_id" required class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"></select></div><div><label class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Periode</label><input name="period" type="text" readonly required class="h-11 w-full cursor-pointer rounded-lg border border-gray-300 bg-transparent px-4 text-sm font-medium text-gray-700 outline-none hover:border-brand-400 focus:border-brand-500 dark:border-gray-700 dark:text-white"></div><div><label class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Nominal budget</label><input name="amount" type="text" inputmode="numeric" data-money-input data-allow-negative="false" required autocomplete="off" placeholder="Rp 0" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"></div><div><label class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Catatan <span class="font-normal text-gray-400">(opsional)</span></label><textarea name="notes" maxlength="250" rows="3" class="w-full rounded-lg border border-gray-300 bg-transparent px-4 py-3 text-sm dark:border-gray-700 dark:text-white"></textarea></div><p data-budget-error class="hidden rounded-lg bg-error-50 px-4 py-3 text-sm text-error-700"></p><div class="flex justify-end gap-3 pt-2"><button data-close-budget-modal type="button" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 dark:border-gray-700 dark:text-gray-300">Batal</button><button type="submit" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-600 disabled:opacity-60">Simpan budget</button></div></form></div></div>
<div data-budget-toast class="app-toast hidden"></div>
@endsection
