import { db } from '../database/database';
import { createEntity, updateEntity } from '../database/entity';

const TYPES = ['boolean', 'count', 'duration'];
export class HabitValidationError extends Error { constructor(message, field = null) { super(message); this.name = 'HabitValidationError'; this.field = field; } }
const dateKey = (date) => date instanceof Date ? date.toLocaleDateString('en-CA') : date;

export class HabitService {
    constructor(database = db) { this.db = database; }
    validate(input) { const name = String(input.name || '').trim(); if (!name) throw new HabitValidationError('Nama kebiasaan wajib diisi.', 'name'); if (name.length > 80) throw new HabitValidationError('Nama maksimal 80 karakter.', 'name'); if (!TYPES.includes(input.tracking_type)) throw new HabitValidationError('Jenis target tidak valid.', 'tracking_type'); const target = input.tracking_type === 'boolean' ? 1 : Number(input.target_value); if (!Number.isSafeInteger(target) || target <= 0 || target > 10000) throw new HabitValidationError('Target kebiasaan tidak valid.', 'target_value'); const days = Array.isArray(input.selected_days) ? input.selected_days.map(Number).filter((day) => day >= 0 && day <= 6) : String(input.selected_days || '').split(',').map(Number).filter((day) => day >= 0 && day <= 6); return { name, icon: [...String(input.icon || '✓').trim()].slice(0, 4).join('') || '✓', color: /^#[0-9a-f]{6}$/i.test(input.color) ? input.color.toLowerCase() : '#12b76a', tracking_type: input.tracking_type, target_value: target, unit: input.tracking_type === 'count' ? String(input.unit || 'kali').trim().slice(0, 20) : input.tracking_type === 'duration' ? 'menit' : null, selected_days: days.length ? days : [0,1,2,3,4,5,6] }; }
    scheduled(habit, date) { return habit.is_active && habit.selected_days.includes(new Date(`${dateKey(date)}T12:00:00`).getDay()); }
    async list(date = new Date()) { const key = dateKey(date); const habits = (await this.db.habits.where('is_active').equals(1).sortBy('sort_order')).filter((habit) => this.scheduled(habit, key)); const logs = await this.db.habit_logs.where('log_date').equals(key).toArray(); const byHabit = new Map(logs.map((log) => [log.habit_id, log])); return Promise.all(habits.map(async (habit) => ({ ...habit, log: byHabit.get(habit.id) || null, value: byHabit.get(habit.id)?.value || 0, is_completed: Boolean(byHabit.get(habit.id)?.is_completed), streak: await this.streak(habit, key), history: await this.history(habit, key) }))); }
    async month(year, month) { const daysInMonth = new Date(year, month, 0).getDate(); const prefix = `${year}-${String(month).padStart(2, '0')}`; const [habits, logs] = await Promise.all([this.db.habits.where('is_active').equals(1).sortBy('sort_order'), this.db.habit_logs.where('log_date').startsWith(prefix).toArray()]); const logMap = new Map(logs.map((log) => [`${log.habit_id}:${log.log_date}`, log])); const today = dateKey(new Date()); const rows = await Promise.all(habits.map(async (habit) => { const days = Array.from({ length: daysInMonth }, (_, index) => { const date = `${prefix}-${String(index + 1).padStart(2, '0')}`; const scheduled = this.scheduled(habit, date); const log = logMap.get(`${habit.id}:${date}`); return { day: index + 1, date, scheduled, future: date > today, completed: Boolean(log?.is_completed), value: log?.value || 0 }; }); const eligible = days.filter((day) => day.scheduled && !day.future); const completed = eligible.filter((day) => day.completed).length; const lastEligibleDay = prefix === today.slice(0, 7) ? Math.min(daysInMonth, Number(today.slice(8, 10))) : daysInMonth; const endDate = `${prefix}-${String(lastEligibleDay).padStart(2, '0')}`; return { ...habit, days, scheduled_count: eligible.length, completed_count: completed, percentage: eligible.length ? Math.round(completed / eligible.length * 100) : 0, streak: await this.streak(habit, endDate) }; })); const scheduledTotal = rows.reduce((sum, row) => sum + row.scheduled_count, 0); const completedTotal = rows.reduce((sum, row) => sum + row.completed_count, 0); return { year, month, daysInMonth, rows, scheduledTotal, completedTotal, percentage: scheduledTotal ? Math.round(completedTotal / scheduledTotal * 100) : 0 }; }
    find(id) { return this.db.habits.get(id); }
    async create(input) { const data = this.validate(input); const item = createEntity({ ...data, profile_id: 'default-profile', frequency: data.selected_days.length === 7 ? 'daily' : 'selected_days', sort_order: await this.db.habits.count(), is_active: 1 }); await this.db.habits.add(item); return item; }
    async update(id, input) { const existing = await this.find(id); if (!existing) throw new HabitValidationError('Kebiasaan tidak ditemukan.'); await this.db.habits.put(updateEntity({ ...existing, ...this.validate({ ...existing, ...input }) })); return this.find(id); }
    async setValue(id, date, value) { const habit = await this.find(id); if (!habit) throw new HabitValidationError('Kebiasaan tidak ditemukan.'); const amount = Math.max(0, Math.min(Number(value) || 0, habit.target_value)); const key = dateKey(date); const existing = await this.db.habit_logs.where('[habit_id+log_date]').equals([id, key]).first(); const values = { ...(existing || {}), habit_id: id, log_date: key, value: amount, is_completed: amount >= habit.target_value ? 1 : 0 }; const log = existing ? updateEntity(values) : createEntity(values); await this.db.habit_logs.put(log); return log; }
    async toggle(id, date) { const habit = await this.find(id); const existing = await this.db.habit_logs.where('[habit_id+log_date]').equals([id, dateKey(date)]).first(); return this.setValue(id, date, existing?.is_completed ? 0 : habit.target_value); }
    async delete(id) { await this.db.transaction('rw', this.db.habits, this.db.habit_logs, async () => { await this.db.habit_logs.where('habit_id').equals(id).delete(); await this.db.habits.delete(id); }); }
    async history(habit, endDate) { const result = []; const date = new Date(`${endDate}T12:00:00`); for (let i = 6; i >= 0; i--) { const day = new Date(date); day.setDate(day.getDate() - i); const key = dateKey(day); const log = await this.db.habit_logs.where('[habit_id+log_date]').equals([habit.id, key]).first(); result.push({ date: key, scheduled: this.scheduled(habit, key), completed: Boolean(log?.is_completed) }); } return result; }
    async streak(habit, endDate) { let streak = 0; const date = new Date(`${endDate}T12:00:00`); for (let i = 0; i < 366; i++) { const key = dateKey(date); if (this.scheduled(habit, key)) { const log = await this.db.habit_logs.where('[habit_id+log_date]').equals([habit.id, key]).first(); if (!log?.is_completed) break; streak++; } date.setDate(date.getDate() - 1); } return streak; }
}
