@extends('layouts.app')

@section('content')
<div data-saving-goal-page class="space-y-6">
    <section class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-sm font-medium text-brand-600">Rencana masa depan</p><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Target Tabungan</h2><p class="mt-1 text-sm text-gray-500">Pantau progres dana yang ingin kamu capai.</p></div><button data-add-goal class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-600">+ Target baru</button></section>
    <section class="grid grid-cols-1 gap-4 sm:grid-cols-3"><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Jumlah target</p><p data-goal-count class="mt-2 text-xl font-bold text-gray-900 dark:text-white">0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Dana terkumpul</p><p data-goal-saved class="mt-2 text-xl font-bold text-success-600">Rp0</p></article><article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">Sisa sasaran aktif</p><p data-goal-remaining class="mt-2 text-xl font-bold text-brand-600">Rp0</p></article></section>
    <section data-goal-list class="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3"><p class="col-span-full py-10 text-center text-sm text-gray-500">Memuat target…</p></section>
</div>

<div data-goal-modal class="app-modal fixed inset-0 z-99999 hidden items-center justify-center overflow-y-auto bg-gray-950/50 p-4" role="dialog" aria-modal="true"><div class="app-modal-panel my-6 w-full max-w-md rounded-2xl bg-white p-6 dark:bg-gray-900"><div class="mb-5 flex items-center justify-between"><h2 data-goal-modal-title class="text-xl font-bold">Target tabungan baru</h2><button data-close-goal-modal class="rounded-lg p-2 text-xl text-gray-400">×</button></div><form id="saving-goal-form" class="space-y-4"><input type="hidden" name="id"><label class="block text-sm font-medium">Nama target<input name="name" required maxlength="80" placeholder="Contoh: Dana darurat" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><label class="block text-sm font-medium">Nominal target<input name="target_amount" type="text" inputmode="numeric" required placeholder="Rp 0" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><label class="block text-sm font-medium">Dana yang sudah terkumpul<input name="saved_amount" type="text" inputmode="numeric" required placeholder="Rp 0" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><label class="block text-sm font-medium">Tanggal target <span class="font-normal text-gray-400">(opsional)</span><input name="target_date" type="text" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><label class="block text-sm font-medium">Catatan <span class="font-normal text-gray-400">(opsional)</span><textarea name="notes" maxlength="250" rows="3" class="mt-1.5 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-3 dark:border-gray-700"></textarea></label><p data-goal-error class="hidden rounded-lg bg-error-50 px-4 py-3 text-sm text-error-700"></p><div class="flex justify-end gap-3"><button data-close-goal-modal type="button" class="rounded-lg border px-4 py-2.5 text-sm">Batal</button><button type="submit" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Simpan target</button></div></form></div></div>
<div data-fund-modal class="app-modal fixed inset-0 z-99999 hidden items-center justify-center bg-gray-950/50 p-4"><div class="app-modal-panel w-full max-w-sm rounded-2xl bg-white p-6 dark:bg-gray-900"><h2 class="text-xl font-bold">Atur dana target</h2><p class="mt-1 text-sm text-gray-500" data-fund-goal-name></p><form id="goal-fund-form" class="mt-5 space-y-4"><input type="hidden" name="id"><label class="block text-sm font-medium">Tindakan<select name="direction" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 dark:border-gray-700"><option value="add">Tambah dana</option><option value="subtract">Kurangi dana</option></select></label><label class="block text-sm font-medium">Nominal<input name="contribution" type="text" inputmode="numeric" required placeholder="Rp 0" class="mt-1.5 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 dark:border-gray-700"></label><div class="flex justify-end gap-3"><button data-close-fund-modal type="button" class="rounded-lg border px-4 py-2.5 text-sm">Batal</button><button class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Simpan dana</button></div></form></div></div>
<div data-goal-toast class="app-toast hidden"></div>
@endsection
